# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "monthly"
      day: "friday"
      time: "22:00"
      timezone: "UTC"
    open-pull-requests-limit: 1
