---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - SQL
DISABLE_LINTERS:
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - RUBY_RUBOCOP
  - TERRAFORM_CHECKOV
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - SPELL_VALE
  - SPELL_LYCHEE
  - SPELL_PROSELINT
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
EXCLUDED_DIRECTORIES:
  - '.history'
  - '.git'
  - '.idea'
  - 'logs'
FILTER_REGEX_EXCLUDE: |
  (?x)(
    \.git/|
    \.history/|
    \.idea/|
    ^vendor/
  )
FILEIO_REPORTER: false
PRE_COMMANDS:
  - command: env
    cwd: 'workspace'
POST_COMMANDS:
  # FIX files set as root user
  # HOST_USER_ID and HOST_GROUP_ID set in package.json
  - command: |
      if [[ "{HOST_USER_ID:-0}" != "0" && "{HOST_GROUP_ID:-0}" != "0" ]]; then
        find . -user 0 -exec chown ${HOST_USER_ID}:${HOST_GROUP_ID} {} ';'
      fi
    cwd: 'workspace'

  # remove files generated by cspell
  - command: find . -name '*megalinter_file_names_cspell.txt' -delete
    cwd: 'workspace'

PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

# Linters configurations
BASH_SHELLCHECK_FILTER_REGEX_EXCLUDE: |
  (?x)(
    ^vendor|
    /testsData/
  )
BASH_SHELLCHECK_ARGUMENTS: --source-path=/tmp/lint
BASH_SHFMT_ARGUMENTS: -i 2 -ci
BASH_SHFMT_FILTER_REGEX_EXCLUDE: .\.zsh$|/\.zshrc|/testsData/|^Gemfile.lock$

CREDENTIALS_SECRETLINT_CONFIG_FILE: .secretlintrc.yml

EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: |
  (?x)(
    \.git/|
    /testsData/.*\.(txt|help)|
    ^manualTests/data/|
    ^src/Log/testsData|
    ^Gemfile.lock$|
    bin/bash-tpl|
    ^doc/guides/Options/generate.*\.md$|
    ^pages/Commands.md
    ^.*-megalinter_file_names_cspell.txt
  )

GIT_GIT_DIFF_PRE_COMMANDS:
  - command: git config --global core.autocrlf input
    continue_if_failed: false
  - command: git config --global core.eol lf
    continue_if_failed: false
  - command: git config --global core.whitespace cr-at-eol,-trailing-space
    continue_if_failed: false
  - command: git config --global core.excludesfile .gitignore
    continue_if_failed: false
  - command: git config --global --add safe.directory .git
    continue_if_failed: false

IGNORE_GITIGNORED_FILES: true
IGNORE_GENERATED_FILES: true

JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
JAVASCRIPT_ES_FILTER_REGEX_EXCLUDE: (report/)

JSON_JSONLINT_FILTER_REGEX_EXCLUDE: |
  (?x)(
    ^\.vscode/(settings|launch)\.json|
    ^conf/\.vscode/settings\.json
  )

MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: (report)

SPELL_CSPELL_FILTER_REGEX_EXCLUDE: (\.git/|\.history/|IDE/.*/.idea|.*-megalinter_file_names_cspell.txt)
SPELL_FILTER_REGEX_EXCLUDE: (\.git/|\.history/|IDE/.*/.idea)
