---
repos:
  - repo: local
    hooks:
      - id: install-requirements
        name: install-requirements
        entry: bash -c './bin/installRequirements'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        stages: [commit]

  - repo: local
    hooks:
      - id: fixShebangExecutionBit
        name: fixShebangExecutionBit
        entry: bash -c './bin/findShebangFiles chmod +x'
        language: system
        always_run: true
        fail_fast: true
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-shebang-scripts-are-executable
        stages: [commit]
      - id: check-xml
        stages: [commit]
      - id: check-yaml
        stages: [commit]
      - id: forbid-new-submodules
        stages: [commit]
      - id: mixed-line-ending
        args: [--fix=lf]
        stages: [commit]
      - id: check-json
        exclude: |
          (?x)^(
            conf\/.vscode\/settings.json|
            .vscode\/launch.json
          )$
        stages: [commit]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
        args: [-i, '2', -ci]
        exclude: |
          (?x)(
            /testsData/|
            ^bin/|
            ^conf/dbScripts/|
            ^install
          )
        stages: [commit]

      # Check both committed and uncommitted files for git conflict
      # markers and whitespace errors according to core.whitespace
      # and conflict-marker-size configuration in a git repo.
      - id: git-check
        exclude: /testsData/
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        stages: [commit]

  - repo: local
    hooks:
      - id: shellcheckLint
        name: shellcheckLint
        entry: bash -c './bin/shellcheckLint --staged -f tty'
        language: system
        always_run: true
        fail_fast: true
        stages: [commit]

  - repo: local
    hooks:
      - id: frameworkLint
        name: frameworkLint
        entry: |
          bash -c './bin/frameworkLint --verbose --expected-warnings-count 6'
        language: system
        always_run: true
        fail_fast: true
        stages: [commit]

  - repo: local
    hooks:
      - id: build-sh-files
        name: build-sh-files
        entry: bash -c './bin/buildBinFiles --ignore-missing'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        stages: [commit]

  - repo: local
    hooks:
      - id: build-doc-files
        name: build-doc-files
        entry: bash -c './bin/doc'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        stages: [push]

  - repo: local
    hooks:
      - id: run-unit-tests
        name: run-unit-tests
        entry: bash -c './bin/test -r src -j 1'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true
        stages: [commit]

  - repo: local
    hooks:
      - id: megalinter-check-version
        name: megalinter-check-version
        language: system
        entry: ./bin/megalinter
        args:
          [
            --image,
            'oxsecurity/megalinter-terraform:v7.5.0',
            --check-megalinter-version,
          ]
        pass_filenames: false
        always_run: true
        fail_fast: true
        stages: [push]

  - repo: local
    hooks:
      - id: megalinter
        name: megalinter
        language: system
        entry: ./bin/megalinter
        args:
          [
            --image,
            'oxsecurity/megalinter-terraform:v7.5.0',
            --config-file,
            '.mega-linter-light.yml',
            --fix,
          ]
        pass_filenames: false
        require_serial: true
        always_run: true
        fail_fast: true
        verbose: true
        stages: [push]
