---
default_stages: [pre-commit, manual]
repos:
  - repo: local
    hooks:
      - id: install-requirements
        name: install-requirements
        entry: bash -c './bin/installRequirements'
        language: system
        always_run: true
        require_serial: true
        fail_fast: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            .svg$
          )
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
        exclude: |
          (?x)^(
            conf\/.vscode\/settings.json|
            .vscode\/settings.json|
            .vscode\/launch.json
          )$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/fchastanet/jumanjihouse-pre-commit-hooks
    rev: 3.0.2
    hooks:
      - id: shfmt
        args: [-i, '2', -ci]
        exclude: |
          (?x)(
            /testsData/|
            ^bin/|
            ^conf/dbScripts/|
            ^install
          )
        stages: [pre-commit]

      # Check both committed and uncommitted files for git conflict
      # markers and whitespace errors according to core.whitespace
      # and conflict-marker-size configuration in a git repo.
      - id: git-check
        exclude: /testsData/

  - repo: https://github.com/fchastanet/bash-tools-framework
    rev: 2.1.0
    hooks:
      - id: fixShebangExecutionBit
      - id: fixShebangExecutionBitGithubActions
      - id: awkLint
      - id: shellcheckLint
      - id: shellcheckLintGithubAction
      - id: frameworkLinter
        args:
          [
            --expected-warnings-count,
            '6',
            --format,
            plain,
            --theme,
            default-force,
            --display-level,
            WARNING,
          ]
      - id: frameworkLinterGithubAction
        args:
          [
            --expected-warnings-count,
            '6',
            --format,
            checkstyle,
            --theme,
            default-force,
            --display-level,
            WARNING,
          ]
      - id: plantuml
      - id: buildShFiles
      - id: buildShFilesGithubAction
      - id: runUnitTests
        args: [-r, src, -j, '1']
        # not manual as github will run UT with several versions of bash and arch
        stages: [pre-commit]
      - id: megalinterCheckVersion
      - id: megalinter
      - id: megalinterGithubAction

  - repo: local
    hooks:
      - &BUILD_DOC_FILES
        id: buildDocFiles
        name: build doc files
        language: script
        entry: bin/doc
        args: [-vvv]
        pass_filenames: false
        require_serial: true
        always_run: true
        fail_fast: true
        stages: [pre-push]
      - <<: *BUILD_DOC_FILES
        id: buildDocFilesGithubAction
        name: build doc files for Github Actions
        fail_fast: false
        stages: [manual]
