language: bash

env:
  - BASH_IMAGE=bash:4.4
  - BASH_IMAGE=bash:5.0.17
  - BASH_IMAGE=bash:rc
  - BASH_IMAGE=amd64/bash:4.4
  - BASH_IMAGE=amd64/bash:5.0.17
  - BASH_IMAGE=amd64/bash:rc

before_script:
  - docker build --build-arg BASH_IMAGE=${BASH_IMAGE} -t git-${BASH_IMAGE} .docker
  - docker pull bash:$BASH
  - docker run bash:$BASH --version

script:
  - docker run --rm -v $PWD:/bash --user $(id -u):$(id -g) git-${BASH_IMAGE} /bash/test.sh