language: bash
services:
  - docker

env:
  matrix:
  - SHELLCHECK=true
  - VENDOR=ubuntu BASH_TAR_VERSION=4.4    BASH_IMAGE=ubuntu:20.04
  - VENDOR=ubuntu BASH_TAR_VERSION=5.0    BASH_IMAGE=ubuntu:20.04
  - VENDOR=ubuntu BASH_TAR_VERSION=5.1    BASH_IMAGE=ubuntu:20.04
  - VENDOR=alpine BASH_TAR_VERSION=4.4    BASH_IMAGE=bash:4.4
  - VENDOR=alpine BASH_TAR_VERSION=5.0.18 BASH_IMAGE=bash:5.0.18
  - VENDOR=alpine BASH_TAR_VERSION=5.1    BASH_IMAGE=bash:5.1

before_script:
  - >
    if [[ "$SHELLCHECK" == 'true' ]]; then
      sudo apt-get install -y shellcheck
    else 
      ./.build/installBuildDeps.sh
      ./.build/buildPushDockerImages.sh "${VENDOR}" "${BASH_TAR_VERSION}" "${BASH_IMAGE}"
    fi

script:
- >
  if [[ "$SHELLCHECK" == 'true' ]]; then
    ./.build/shellcheck.sh > shellcheck.log
    ./.build/publishDeepsourceArtifact.sh ./shellcheck.log
    ./doc.sh
    if ! git diff-index --quiet HEAD --; then
      (>&2 echo "doc needs to be updated")
      exit 1
    fi
  else
    ./test.sh
  fi