---
name: 'Bash Tools Pre-Build Setup'
description: 'Sets up Docker environment and vendor dependencies for bash-tools documentation build'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker pull image
      shell: bash
      run: docker pull scrasnups/build:bash-tools-ubuntu-5.1

    - name: Install vendors
      shell: bash
      run: |
        set -exo pipefail
        ./bin/installRequirements

    - name: Check if doc up to date
      shell: bash
      run: |
        ./bin/doc --ci
