ARG BASH_IMAGE=amd64/bash:5.0.17
FROM ${BASH_IMAGE}

RUN apk add --no-cache git
ENV IN_BASH_DOCKER="You're in docker"

ONBUILD ARG USER_ID=1000
ONBUILD ARG GROUP_ID=1000
ONBUILD RUN set -x \
    && addgroup -g ${GROUP_ID} -S www-data \
    && adduser -u ${USER_ID} -D -S -h /app -s /sbin/nologin -G www-data www-data
