#!/usr/bin/env bash

# shellcheck disable=SC2034
NAME="Ubuntu"
# shellcheck disable=SC2034
VERSION="20.04.5 LTS (Focal Fossa)"
# shellcheck disable=SC2034
ID=ubuntu
# shellcheck disable=SC2034
ID_LIKE=debian
# shellcheck disable=SC2034
PRETTY_NAME="Ubuntu 20.04.5 LTS"
# shellcheck disable=SC2034
VERSION_ID="20.04"
# shellcheck disable=SC2034
HOME_URL="https://www.ubuntu.com/"
# shellcheck disable=SC2034
SUPPORT_URL="https://help.ubuntu.com/"
# shellcheck disable=SC2034
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
# shellcheck disable=SC2034
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
# shellcheck disable=SC2034
VERSION_CODENAME=focal
# shellcheck disable=SC2034
UBUNTU_CODENAME=focal
