---
# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
# Check if precommit packages need to be updated and create PR if this is the case
name: Pre-commit auto-update
on:
  workflow_dispatch:
  schedule:
    # https://crontab.cronhub.io/
    - cron: '30 10 * * *'

permissions: read-all

jobs:
  auto-update:
    runs-on: ubuntu-22.04
    steps:
      # kics-scan ignore-line
      - uses: actions/checkout@v4

      - name: Set up Python
        # kics-scan ignore-line
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create Pull Request
        # kics-scan ignore-line
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update/pre-commit-autoupdate
          title: Auto-update pre-commit hooks
          commit-message: Auto-update pre-commit hooks
          body: |
            Update versions of tools in pre-commit
            configs to latest version
          labels: dependencies
