name: Workflow executed at each push
on:
  push:
  pull_request:
  workflow_dispatch:
    

jobs:
  
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: mkdir -p logs
        working-directory: ./
      - name: Linting - Shellcheck
        run: ./shellcheck.sh | tee logs/shellcheck-checkstyle.xml
        working-directory: ./
      - name: Linting - Awk
        run: ./awkLint.sh | tee logs/awkLint.log
        working-directory: ./
      - name: Linting - Dockerfiles
        run: ./dockerLint.sh | tee logs/docker-checkstyle.xml
        working-directory: ./
      - uses: actions/checkout@v2
        with:
          name: fchastanet/tomdoc.sh
          path: vendor/fchastanet.tomdoc.sh
          ref: refs/heads/master
      - name: Check if doc up to date
        run: |
          ./doc.sh
          if ! git diff --exit-code >/dev/null; then
            (>&2 echo "Documentation not up to date, please run doc.sh to update it")
            exit 1
          fi
        working-directory: ./
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'logs/*-checkstyle.xml'
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: linter-reports
          path: |
            logs/*.xml
            logs/*.log
