name: Workflow executed at each push
on:
  push:
  pull_request:
  workflow_dispatch:
    

jobs:
  
  linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Shellcheck
        run: ./shellcheck.sh | tee logs/shellcheck-checkstyle.xml
        working-directory: ./
      - run: ./awkLint.sh | tee logs/awkLint.log
        working-directory: ./
      - run: ./dockerLint.sh | tee logs/docker-checkstyle.xml
        working-directory: ./
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'logs/*-checkstyle.xml'
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: linter-reports
          path: |
            logs/*.xml
            logs/*.log
