name: Workflow executed at each push
on:
  push:
  pull_request:
  workflow_dispatch:
    

jobs:
  
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Shellcheck
        run: ./shellcheck.sh
        working-directory: ./

  dockerLint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Hadolint
        uses: jbergstroem/hadolint-gh-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dockerfile: ".build/Dockerfile*"
          output_format: checkstyle
  
  awkLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: ./awkLint.sh > awkLint.log
        working-directory: ./

  
